-- MySQL Script generated by MySQL Workbench
-- Fri Jul  4 22:45:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bird_migration
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bird_migration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bird_migration` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bird_migration` ;

-- -----------------------------------------------------
-- Table `bird_migration`.`birds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bird_migration`.`birds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `common_name` VARCHAR(100) NOT NULL,
  `scientific_name` VARCHAR(100) NULL DEFAULT NULL,
  `family` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bird_migration`.`conservation_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bird_migration`.`conservation_status` (
  `bird_id` INT NOT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`bird_id`),
  CONSTRAINT `conservation_status_ibfk_1`
    FOREIGN KEY (`bird_id`)
    REFERENCES `bird_migration`.`birds` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bird_migration`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bird_migration`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NULL DEFAULT NULL,
  `latitude` DECIMAL(9,6) NULL DEFAULT NULL,
  `longitude` DECIMAL(9,6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bird_migration`.`migration_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bird_migration`.`migration_routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_name` VARCHAR(100) NOT NULL,
  `season` VARCHAR(20) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bird_migration`.`sightings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bird_migration`.`sightings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bird_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `route_id` INT NULL DEFAULT NULL,
  `sighting_date` DATE NULL DEFAULT NULL,
  `observer_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `bird_id` (`bird_id` ASC) VISIBLE,
  INDEX `location_id` (`location_id` ASC) VISIBLE,
  INDEX `route_id` (`route_id` ASC) VISIBLE,
  CONSTRAINT `sightings_ibfk_1`
    FOREIGN KEY (`bird_id`)
    REFERENCES `bird_migration`.`birds` (`id`),
  CONSTRAINT `sightings_ibfk_2`
    FOREIGN KEY (`location_id`)
    REFERENCES `bird_migration`.`locations` (`id`),
  CONSTRAINT `sightings_ibfk_3`
    FOREIGN KEY (`route_id`)
    REFERENCES `bird_migration`.`migration_routes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
